spring.application.name=Doc_storage_API

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=2GB

# --- Database Config ---
# Notice we can even make the URL dynamic if we want, but usually, just the secrets are enough.
spring.datasource.url=jdbc:postgresql://localhost:5433/sentinel_db

# READ FROM ENVIRONMENT VARIABLES
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect